# Generated by Django 3.2.5 on 2021-08-18 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_article_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourceowner', to=settings.AUTH_USER_MODEL)),
                ('sources', models.ManyToManyField(to='news.Source')),
            ],
        ),
    ]
