# Generated by Django 3.2.5 on 2021-08-14 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_auto_20210814_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='saved',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
